'use client';

import { useState } from 'react';
import Image from 'next/image';
import StarRating from './StarRating';
import { ResultImage, ImageRating } from '@/types';

interface ImageRatingGridProps {
  taskId: string;
  resultImages: ResultImage[];
  existingRatings: ImageRating[];
}

export default function ImageRatingGrid({
  taskId,
  resultImages,
  existingRatings,
}: ImageRatingGridProps) {
  const [expandedImagePath, setExpandedImagePath] = useState<string | null>(null);
  const [ratings, setRatings] = useState<Map<string, Partial<ImageRating>>>(
    new Map(
      existingRatings.map((r) => [
        r.imagePath,
        {
          overallRating: r.overallRating,
          imageQuality: r.imageQuality || 0,
          styleMatch: r.styleMatch || 0,
          productFidelity: r.productFidelity || 0,
          creativity: r.creativity || 0,
          comment: r.comment || '',
        },
      ])
    )
  );
  const [savingImages, setSavingImages] = useState<Set<string>>(new Set());

  // 只显示成功生成的图片
  const validImages = resultImages.filter((img) => img.path);

  const handleRatingChange = async (
    image: ResultImage,
    field: string,
    value: number | string
  ) => {
    const imagePath = image.path!;
    const currentRating = ratings.get(imagePath) || {};
    const newRating = { ...currentRating, [field]: value };

    setRatings(new Map(ratings.set(imagePath, newRating)));

    // 如果有整体评分，立即保存
    if (newRating.overallRating && newRating.overallRating > 0) {
      setSavingImages(new Set(savingImages).add(imagePath));

      try {
        const response = await fetch('/api/ratings/image', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            taskId,
            imagePath,
            modelId: image.model,
            provider: image.provider,
            overallRating: newRating.overallRating,
            imageQuality: newRating.imageQuality || null,
            styleMatch: newRating.styleMatch || null,
            productFidelity: newRating.productFidelity || null,
            creativity: newRating.creativity || null,
            comment: newRating.comment || null,
          }),
        });

        if (!response.ok) {
          console.error('保存评分失败');
        }
      } catch (error) {
        console.error('保存评分失败:', error);
      } finally {
        setSavingImages((prev) => {
          const next = new Set(prev);
          next.delete(imagePath);
          return next;
        });
      }
    }
  };

  const getRating = (imagePath: string) => {
    return ratings.get(imagePath) || { overallRating: 0 };
  };

  const isExpanded = (imagePath: string) => expandedImagePath === imagePath;

  const toggleExpand = (imagePath: string) => {
    setExpandedImagePath(isExpanded(imagePath) ? null : imagePath);
  };

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {validImages.map((image) => {
        const imagePath = image.path!;
        const rating = getRating(imagePath);
        const expanded = isExpanded(imagePath);
        const isSaving = savingImages.has(imagePath);

        return (
          <div
            key={imagePath}
            className="border border-gray-200 rounded-lg overflow-hidden hover:shadow-lg transition-shadow"
          >
            {/* 图片预览 */}
            <div className="relative aspect-square bg-gray-100">
              <Image
                src={imagePath}
                alt={`Generated by ${image.model}`}
                fill
                className="object-contain"
              />
            </div>

            {/* 模型信息 */}
            <div className="p-4 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium text-gray-700 truncate">
                  {image.model}
                </span>
                {isSaving && (
                  <div className="animate-spin rounded-full h-4 w-4 border-2 border-blue-500 border-t-transparent"></div>
                )}
              </div>

              {/* 快速评分 */}
              <div>
                <label className="block text-xs text-gray-500 mb-1">快速评分</label>
                <StarRating
                  value={rating.overallRating || 0}
                  onChange={(value) =>
                    handleRatingChange(image, 'overallRating', value)
                  }
                  size="small"
                />
              </div>

              {/* 展开详情按钮 */}
              <button
                type="button"
                onClick={() => toggleExpand(imagePath)}
                className="text-sm text-blue-600 hover:text-blue-700 flex items-center gap-1"
              >
                {expanded ? '收起详情' : '展开详情'}
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={2}
                  stroke="currentColor"
                  className={`w-4 h-4 transition-transform ${
                    expanded ? 'rotate-180' : ''
                  }`}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M19.5 8.25l-7.5 7.5-7.5-7.5"
                  />
                </svg>
              </button>

              {/* 多维度评分（展开） */}
              {expanded && (
                <div className="space-y-3 pt-3 border-t border-gray-200">
                  <div>
                    <label className="block text-xs text-gray-600 mb-1">
                      图像质量
                    </label>
                    <StarRating
                      value={rating.imageQuality || 0}
                      onChange={(value) =>
                        handleRatingChange(image, 'imageQuality', value)
                      }
                      size="small"
                    />
                  </div>

                  <div>
                    <label className="block text-xs text-gray-600 mb-1">
                      风格匹配度
                    </label>
                    <StarRating
                      value={rating.styleMatch || 0}
                      onChange={(value) =>
                        handleRatingChange(image, 'styleMatch', value)
                      }
                      size="small"
                    />
                  </div>

                  <div>
                    <label className="block text-xs text-gray-600 mb-1">
                      商品还原度
                    </label>
                    <StarRating
                      value={rating.productFidelity || 0}
                      onChange={(value) =>
                        handleRatingChange(image, 'productFidelity', value)
                      }
                      size="small"
                    />
                  </div>

                  <div>
                    <label className="block text-xs text-gray-600 mb-1">
                      创意性
                    </label>
                    <StarRating
                      value={rating.creativity || 0}
                      onChange={(value) =>
                        handleRatingChange(image, 'creativity', value)
                      }
                      size="small"
                    />
                  </div>

                  <div>
                    <label className="block text-xs text-gray-600 mb-1">
                      评论
                    </label>
                    <textarea
                      value={rating.comment || ''}
                      onChange={(e) =>
                        handleRatingChange(image, 'comment', e.target.value)
                      }
                      className="w-full p-2 text-sm border border-gray-300 rounded focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
                      rows={3}
                      placeholder="写下您的想法..."
                    />
                  </div>
                </div>
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
}
